var statsData = {
    "type": "bar",
        "data": {
        "labels": [
            "2016-04-08 Fri",
            "2016-04-09 Sat",
            "2016-04-10 Sun",
            "2016-04-11 Mon",
            "2016-04-12 Tue",
            "2016-04-13 Wed",
            "2016-04-14 Thu",
            "2016-04-15 Fri",
            "2016-04-16 Sat",
            "2016-04-17 Sun",
            "2016-04-18 Mon",
            "2016-04-19 Tue",
            "2016-04-20 Wed",
            "2016-04-21 Thu",
            "2016-04-22 Fri",
            "2016-04-23 Sat",
            "2016-04-24 Sun",
            "2016-04-25 Mon",
            "2016-04-26 Tue",
            "2016-04-27 Wed",
            "2016-04-28 Thu",
            "2016-04-29 Fri",
            "2016-04-30 Sat",
            "2016-05-01 Sun",
            "2016-05-02 Mon",
            "2016-05-03 Tue"
        ],
            "datasets": [
            {
                "backgroundColor": "rgba(0,0,0,0)",
                "type": "line",
                "borderColor": "rgba(256,0,256,1)",
                "borderWidth": 1,
                "label": "weight",
                "pointHoverRadius": 2,
                "pointRadius": 0,
                "data": [
                    166,
                    166,
                    165.5,
                    166,
                    163.5,
                    163.6,
                    159.5,
                    161,
                    163,
                    163.5,
                    163,
                    162,
                    162.5,
                    162,
                    162.5,
                    163.5,
                    163.5,
                    163.5,
                    165,
                    164.5,
                    164,
                    164,
                    164,
                    163,
                    null,
                    null
                ]
            },
            {
                "backgroundColor": "rgba(0,0,0,0)",
                "type": "line",
                "borderColor": "rgba(0,0,0,1)",
                "borderWidth": 1,
                "label": "heartrate",
                "pointHoverRadius": 2,
                "pointRadius": 0,
                "data": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    100,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    68,
                    79,
                    77,
                    null,
                    null
                ]
            },
            {
                "backgroundColor": [
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#90ee90",
                    "#9cf080",
                    "#90ee90",
                    "#ffffff",
                    "#ffffff"
                ],
                "type": "bar",
                "borderColor": "rgba(0,0,0,1)",
                "borderWidth": 0,
                "label": "diastolic",
                "pointHoverRadius": 2,
                "pointRadius": 0,
                "data": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    73,
                    79,
                    77,
                    null,
                    null
                ]
            },
            {
                "backgroundColor": [
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#ffffff",
                    "#daf930",
                    "#ffdf00",
                    "#ffff00",
                    "#ffffff",
                    "#ffffff"
                ],
                "type": "bar",
                "borderColor": "rgba(0,0,0,1)",
                "borderWidth": 0,
                "label": "systolic",
                "pointHoverRadius": 2,
                "pointRadius": 0,
                "data": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    120,
                    139,
                    134,
                    null,
                    null
                ]
            }
        ]
    },
    "options": {
        "hover": { "mode": "label" },
        "responsive": true,
            "scales": {
            "xAxes": [
                {
                    "barPercentage": 1,
                    "categorySpacing": 0,
                    "stacked": true,
                    "gridLines": {
                        "display": false
                    }
                }
            ],
                "yAxes": [
                {
                    "stacked": true
                }
            ]
        },
        "tooltips": {
            "mode": "label"
        }
    }
}